src/main/java/seedu/address/model/person/Developer.java
src/main/java/seedu/address/model/person/ProjectManager.java
src/main/java/seedu/address/model/person/Team.java
src/main/java/seedu/address/model/person/TeamLeader.java
src/test/java/seedu/address/model/person/DeveloperTest.java
src/test/java/seedu/address/model/person/ProjectManagerTest.java
src/test/java/seedu/address/model/person/TeamLeaderTest.java
src/test/java/seedu/address/model/person/TeamTest.java

Add ProjectManager class
Add Team class
Add Teamleader class
Add Developer(Team members) class.

Add multiple classes for better distinction

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/HelpCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/Remark.java
src/main/java/seedu/address/model/person/Team.java
src/main/java/seedu/address/model/person/UniquePersonList.java
src/test/java/seedu/address/testutil/PersonUtil.java

Complete the 'remark' command such that it supports adding using 'add', and it is optional; also supports editing using edit. Will update the corresponding test soon.
The second commit fixed check-style errors.

Complete the 'remark' command

---

build.gradle
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/ReadOnlyAddressBook.java
src/main/java/seedu/address/model/person/Team.java
src/main/java/seedu/address/model/person/UniquePersonList.java
src/main/java/seedu/address/model/person/UniqueTeamList.java
src/main/java/seedu/address/model/person/exceptions/DuplicateTeamException.java
src/main/java/seedu/address/model/person/exceptions/TeamNotFoundException.java
src/test/java/seedu/address/model/person/TeamTest.java

Updated AddressBook and ModelManager accordingly.

Added UniqueTeamList class.

---

src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/commands/CommandResult.java
src/main/java/seedu/address/logic/commands/ExitCommand.java
src/main/java/seedu/address/logic/commands/HelpCommand.java
src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/commands/ListTeamCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/TeamBook.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/java/seedu/address/ui/TeamCard.java
src/main/java/seedu/address/ui/TeamListPanel.java
src/main/resources/view/MainWindow.fxml
src/main/resources/view/TeamListCard.fxml
src/main/resources/view/TeamListPanel.fxml

The "listt" command for now is able to list all teams by displaying team name, index and developer's indices. Will update soon to make it display all names, also in a nicer orientation.

Add "listt" command which allows listing all existing teams

---

src/main/resources/view/MainWindow.fxml

Fix full screen bottom cut-off problem

Fix full screen bottom cut-off problem

---

src/main/java/seedu/address/logic/commands/AddDevToTeamCommand.java
src/main/java/seedu/address/logic/commands/DeleteDeveloperFromTeamCommand.java
src/main/java/seedu/address/logic/parser/AddDevToTeamParser.java
src/main/java/seedu/address/logic/parser/AddTeamCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java

Fixed the bugs with delete and add commands.

Branch fix delete bug

---

src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/TeamCard.java
src/main/resources/view/MainWindow.fxml
src/main/resources/view/TeamListCard.fxml

Display developer list and team list side by side by default, the list and listt commands still work

Display developer list and team list side by side by default

---

src/main/java/seedu/address/logic/commands/AddDevToTeamCommand.java
src/main/java/seedu/address/logic/commands/CommandResult.java
src/main/java/seedu/address/logic/commands/ExitCommand.java
src/main/java/seedu/address/logic/commands/HelpCommand.java
src/main/java/seedu/address/logic/commands/ListTeamCommand.java
src/main/java/seedu/address/logic/commands/TreeCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/resources/view/MainWindow.fxml

Added 'tree' command and area for displaying the tree. To exist from the tree view: just enter 'tree' again.

Add a tree command and area for displaying tree

---

src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/TeamCard.java
src/main/java/seedu/address/ui/TeamListPanel.java
src/main/resources/view/MainWindow.fxml
src/test/java/seedu/address/logic/commands/CommandResultTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/ExitCommandTest.java
src/test/java/seedu/address/logic/commands/HelpCommandTest.java

Add statistics display; allow team list to display person's name

Add statistics display; allow team list to display person's name

---

docs/UserGuide.md

The Edit command in UG is not changed after some new Edit commands are introduced.
Users will not know the new Edit commands from current UG.
Updating Edit command in UG allows users to learn how to use new Edit commands.
Let's update the Edit Commands in UG to support smooth usage of our application for our users.

User Guide: update Edit commands

---

build.gradle
src/test/java/seedu/address/testutil/PersonUtil.java

Fix the parseCommand_add() test in AddressBookParserTest

Fix the parseCommand_add() test in AddressBookParserTest

---

src/main/java/seedu/address/ui/MainWindow.java

Fix a bug in the tree command

---

docs/DeveloperGuide.md

Modified developer guide with new user stories, NFR, use cases and added implementation of `newteam` command.

Modify developer guide.

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/ui/LinkTreeDisplay.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/TeamStructureDisplay.java
src/main/resources/view/LinkTreeDisplay.fxml
src/main/resources/view/TeamStructureDisplay.fxml

Our hierarchy of contact information are not visualizable.
Visualization of hierachy of contact information aids the user to make decisions.
Visualizing the tree structure provides a general hierarchical view of all the contact information, which helps users to decide who to contact.
Let's have a "tree" command that allows users to see the tree structure in a new window.
Displaying in a new window allows bigger display of the tree structure so that users can navigate easily.

Tree Command: Display LinkTree in A New Window

---

src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/commands/FindTeamCommand.java
src/main/java/seedu/address/logic/commands/FindTeamLeaderCommand.java

Update: Revamped GUI Integration for "Find" Command Functionality
- Enhanced user interface interactions for the general `FindCommand.java`.
- Optimized visualization and feedback mechanisms for the `FindTeamCommand.java`, ensuring users receive clear and concise results when searching for teams.
- Overhauled the graphical representation and output for `FindTeamLeaderCommand.java`, enhancing the user experience when locating team leaders within the application.
These GUI updates provide a more intuitive and streamlined user experience, allowing for easier navigation and improved efficiency when utilizing the "find" commands.

Update: Revamped GUI Integration for "Find" Command Functionality

---

src/main/java/seedu/address/logic/commands/AddDevToTeamCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/ui/LinkTreeDisplay.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/TeamListPanel.java
src/main/resources/view/LinkTreeDisplay.fxml
src/main/resources/view/TeamStructureDisplay.fxml

There will be a NullPointerException after using edit command to change a person's information. Becuase edit command will create a new person object which will have a new Identity code, old Identity code stored in the team book cannot refer to the edited person which has a new Identity code.
The tree command cannot work with the exception present.
Let's fix this bug so that "LinkTree" can be shown properly after edit command. Let's have new person constructor that instantiate a person object with a given identity code.
Therefore, edit command can create a new person object with original Identity code.

Fix Bug: Crash after Edit Command

---

src/main/java/seedu/address/ui/HelpWindow.java
src/main/java/seedu/address/ui/MainWindow.java

Fix the problem with help message not showing when pressing 'F1'

Fix the problem with help message not showing when pressing 'F1'

---

src/main/java/seedu/address/logic/commands/CommandResult.java
src/main/java/seedu/address/logic/commands/ExitCommand.java
src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/commands/FindTeamCommand.java
src/main/java/seedu/address/logic/commands/FindTeamLeaderCommand.java
src/main/java/seedu/address/logic/commands/HelpCommand.java
src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/commands/ListTeamCommand.java
src/main/java/seedu/address/logic/commands/TreeCommand.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/TeamCard.java

This commit addresses several bugs and issues in the FindTeamCommand and FindTeamLeaderCommand classes.
These fixes improve the reliability and accuracy of both FindTeamCommand and FindTeamLeaderCommand, ensuring that they work as intended and provide better user feedback when encountering issues. Unit tests have also been updated to cover these scenarios to prevent regressions in the future.

Fix FindTeamCommand and FindTeamLeaderCommand Bugs

---

src/main/java/seedu/address/logic/commands/RemarkCommand.java
src/test/java/seedu/address/logic/commands/RemarkCommandTest.java

fix bugs related to remark and add test for remark command

Branch bugfix remark

---

src/test/java/seedu/address/logic/commands/RemarkCommandTest.java

fix check-style

---

build.gradle
src/main/java/seedu/address/logic/commands/HelpCommand.java
src/main/java/seedu/address/ui/TeamCard.java
src/main/resources/view/PersonListCard.fxml
src/main/resources/view/TeamListCard.fxml
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/ListTeamCommandTest.java
src/test/java/seedu/address/testutil/TypicalIndexes.java
src/test/java/seedu/address/ui/MainWindowTest.java

fix helpCommand, person list and team list attribute cut-off problem; add test for list team and mainWindow

Branch UI bug

---

src/main/java/seedu/address/logic/commands/HelpCommand.java
src/test/java/seedu/address/logic/commands/TreeCommandTest.java

Undo the addition of help message shown, add test for TreeCommand

Branch undo helpmessage addition

---

docs/UserGuide.md

Specify the exact behaviour of some commands in the UG (words after some commands will be ignored)

Changes in UG

---

docs/UserGuide.md

The tree command has some behaviors that are mistook as bugs.
Those are expected behaviors which users should be aware of.
Let's update the tree command note in UG to notify the users.
Users will not be too surprised by the expected behaviors with the help of a note.

UG Tree Command Notes: update

---

docs/UserGuide.md
docs/team/tang-moyan.md

PPP is still just a template.
A updated PPP can better reflect ones contribution.
Let's put more information about what I have contributed.
Clear contribution is good for the team management.

PPP: update

---

.gitignore
docs/UserGuide.md

Add icons for notes, tips and warnings

Add icons for notes, tips and warnings

---

docs/UserGuide.md

Update 'how to use this guide' and 'getting started'

Update 'how to use this guide' and 'getting started'

---

docs/team/jizhuochen.md

updated PPP

---

src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/EditTeamLeaderCommandTest.java
src/test/java/seedu/address/logic/parser/AddTeamCommandParserTest.java
src/test/java/seedu/address/logic/parser/EditTeamLeaderCommandParserTest.java
src/test/java/seedu/address/logic/parser/EditTeamNameCommandParserTest.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Some edit commands and their parsers do not have tests.
Having tests can enforce some functionalities.
Let's add tests to test their behaviors.
Those behaviors will be enforced by the tests despite future development of the codes.

More Testing: edit commands and their parsers

---

docs/DeveloperGuide.md
docs/diagrams/AddDevToTeamCommandDiagram.puml
docs/diagrams/AddTeamCommandDiagram.puml

Make changes to DG and add PUML diagrams for create team and add dev to team.

Make changes to DG and add PUML diagrams for create team and add

---

docs/AboutUs.md
docs/DeveloperGuide.md
docs/UserGuide.md
docs/team/tang-moyan.md
src/main/java/seedu/address/logic/commands/EditTeamNameCommand.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/logic/commands/EditTeamLeaderCommandTest.java
src/test/java/seedu/address/logic/commands/EditTeamNameCommandTest.java

Some edit commands are not fully tested.
Having tests can enforce some functionalities.
Let's add tests to test all their behaviors.
Those behaviors will be enforced by the tests despite future development of the codes.

More Testing: edit commands

---

docs/DeveloperGuide.md
docs/diagrams/ListCommandDiagram.puml
docs/diagrams/ListTeamCommandDiagram.puml
docs/team/jizhuochen.md

Branch DG2

---

docs/team/erohsikivar.md
docs/team/tang-moyan.md

PPP is still not finished yet.
A updated PPP can better reflect ones contribution.
Let's put more information about what I have contributed.
Clear contribution is good for the team management.

PPP: update2

---

docs/DeveloperGuide.md

Add instruction for manual testing into DG

Add instruction for manual testing into DG

---

docs/DeveloperGuide.md

fix checkstyle
